import { ColumnSettings } from 'handsontable/settings';
import { environment } from '../../environments/environment';
import { customValidationDropdownRenderer, formatDates } from './utils';

const API_URL = environment.apiUrl;

export const API = {
  SIGN_IN: API_URL + '/admin/login',
  AUTH: API_URL + '/admin/me',
  GET_USERS: API_URL + '/admin/users',
  DOWNLOAD_USERS: API_URL + '/admin/users/download',
  GET_ANNOUNCEMENTS: API_URL + '/announcements',
  CREATE_ANNOUNCEMENT: API_URL + '/admin/announcements/new',
  UPDATE_ANNOUNCEMENT: API_URL + '/admin/announcements/update',
  DELETE_ANNOUNCEMENT: API_URL + '/admin/announcements/delete',
  GET_BLOGS: API_URL + '/blogs',
  CREATE_BLOG: API_URL + '/admin/blogs/new',
  GET_BLOG: (id: string) => API_URL + '/blogs/' + id,
  UPDATE_BLOG: (id: string) => API_URL + '/admin/blogs/' + id + '/edit',
  DELETE_BLOG: (id: string) => API_URL + '/admin/blogs/' + id + '/delete',
  HOME: API_URL + '/admin/dashboard',
  GET_SLOT_BOOKINGS: API_URL + '/admin/slot-bookings',
  MARK_ATTENDANCE_SLOT_BOOKING: (id: string) =>
    API_URL + '/admin/slot-bookings/' + id + '/attendance',
  GET_TELECALLERS: API_URL + '/admin/telecallers',
  CREATE_TELECALLER: API_URL + '/admin/telecallers/new',
  UPDATE_TELECALLER: (id: string) => API_URL + '/admin/telecallers/' + id + '/edit',
  GET_TELECALLER_BOOKINGS: API_URL + '/admin/telecallers/bookings',
  UPLOAD_TELECALLER_BOOKINGS: API_URL + '/admin/telecallers/bookings/upload',
  UPDATE_TELECALLER_BOOKINGS: API_URL + '/admin/telecallers/bookings/update',
  UPDATE_TELECALLER_BOOKINGS_ACTIVATION_STATUS: API_URL + '/admin/telecallers/bookings/activation',
  ASSIGN_TELECALLER_BOOKINGS: API_URL + '/admin/telecallers/bookings/assign',
  GET_REFERRERS: API_URL + '/admin/referrers',
  GET_REFERRER_BY_ID: (id: string) => API_URL + '/admin/referrers/' + id,
  TOGGLE_ACTIVATION: (id: string) => API_URL + '/admin/referrers/' + id + '/toggle-activation',
  GET_ATTENDEES: API_URL + '/admin/attendees',
  DOWNLOAD_ATTENDEES: API_URL + '/admin/attendees/download',
  MARK_ATTENDANCE_ATTENDEE: (id: string) => API_URL + '/admin/attendees/' + id + '/attendance',
  GET_ADMISSIONS_QUERIES: API_URL + '/admin/admission-query',
  DOWNLOAD_ADMISSIONS_QUERIES: API_URL + '/admin/admission-query/download',
  MARK_ATTENDANCE_ADMISSION_QUERY: (id: string) =>
    API_URL + '/admin/admission-query/' + id + '/attendance',
};

export const TELECALLER_BOOKINGS_ADMIN_HOT_COLUMNS: ColumnSettings[] = [
  { data: '_id', title: '_Id', width: 0 },
  { data: 'isDeactivated', title: 'Deactivated', width: 0 },
  { title: 'Select', type: 'checkbox', data: 'select', width: 85 },
  { data: 'refNo', title: 'Ref no', width: 95 },
  { data: 'studentName', title: 'Student name', width: 173 },
  { data: 'parentName', title: 'Parent name', width: 196 },
  {
    data: 'assignedTo',
    title: 'Assigned To',
    valueGetter(value, row, column, cellProperties) {
      return value && Array.isArray(value) ? value.map((user) => user.name).join(', ') : '';
    },
    width: 283,
    readOnly: true,
  },
  { data: 'fatherOccupation', title: 'Father occupation', width: 153 },
  { data: 'mobile', title: 'Mobile', width: 100 },
  { data: 'alternateMobile', title: 'Alternate mobile', width: 145 },
  { data: 'school', title: 'School', width: 253 },
  { data: 'board', title: 'Board', width: 85 },
  { data: 'schoolType', title: 'School Type', width: 125 },
  {
    data: 'subjects',
    title: 'Subjects',
    valueFormatter: (value: string[]) => {
      return value && Array.isArray(value) ? value.join(', ') : '';
    },
    width: 283,
  },
  { data: 'community', title: 'Community', width: 125 },
  { data: 'area', title: 'Area', width: 80 },
  { data: 'district', title: 'District', width: 100 },
  { data: 'domainInterest', title: 'Domain interest', width: 155 },
  { data: 'courseInterest', title: 'Course interest', width: 155 },
  {
    data: 'dataValidationStatus',
    title: 'Data validation status',
    type: 'dropdown',
    allowInvalid: false,
    allowEmpty: false,
    source: ['correct', 'incorrect', 'partial'],
    renderer: customValidationDropdownRenderer,
    width: 190,
  },
  { data: 'isAdmissionComplete', title: 'Admission Complete', width: 150, type: 'checkbox' },
  { data: 'remarks', title: 'Remarks', width: 100 },
  {
    data: 'createdAt',
    title: 'Created at',
    readOnly: true,
    width: 150,
    valueFormatter(value: string) {
      return formatDates(value);
    },
  },
  {
    data: 'updatedAt',
    title: 'Updated at',
    readOnly: true,
    width: 150,
    valueFormatter(value: string) {
      return formatDates(value);
    },
  },
];

export const TELECALLER_BOOKINGS_TELECALLER_HOT_COLUMNS: ColumnSettings[] = [
  { data: '_id', title: '_Id', width: 0 },
  { data: 'isDeactivated', title: 'Deactivated', width: 0 },
  { title: 'Select', type: 'checkbox', data: 'select', width: 85 },
  { data: 'refNo', title: 'Ref no', width: 95 },
  { data: 'studentName', title: 'Student name', width: 173 },
  { data: 'parentName', title: 'Parent name', width: 196 },
  { data: 'fatherOccupation', title: 'Father occupation', width: 153 },
  { data: 'mobile', title: 'Mobile', width: 100 },
  { data: 'alternateMobile', title: 'Alternate mobile', width: 145 },
  { data: 'school', title: 'School', width: 253 },
  { data: 'board', title: 'Board', width: 85 },
  { data: 'schoolType', title: 'School Type', width: 125 },
  {
    data: 'subjects',
    title: 'Subjects',
    valueFormatter: (value: string[]) => {
      return value && Array.isArray(value) ? value.join(', ') : '';
    },
    width: 283,
  },
  { data: 'community', title: 'Community', width: 125 },
  { data: 'area', title: 'Area', width: 80 },
  { data: 'district', title: 'District', width: 100 },
  { data: 'domainInterest', title: 'Domain interest', width: 155 },
  { data: 'courseInterest', title: 'Course interest', width: 155 },
  {
    data: 'dataValidationStatus',
    title: 'Data validation status',
    type: 'dropdown',
    allowInvalid: false,
    allowEmpty: false,
    source: ['correct', 'incorrect', 'partial'],
    renderer: customValidationDropdownRenderer,
    width: 190,
  },
  { data: 'remarks', title: 'Remarks', width: 100 },
  {
    data: 'assignedAt',
    title: 'Assigned at',
    width: 150,
    readOnly: true,
    valueFormatter(value: string) {
      return formatDates(value);
    },
  },
];

export const COLLEGE_COURSE_GROUPS = {
  'COMPUTER SCIENCE AND ENGINEERING': [
    {
      'S NO': 1,
      'Branch Code': 'CS',
      'Branch Name': 'COMPUTER SCIENCE AND ENGINEERING',
      Cateogry: 1,
    },
    {
      'S NO': 2,
      'Branch Code': 'IT',
      'Branch Name': 'INFORMATION TECHNOLOGY',
      Cateogry: 1,
    },
    {
      'S NO': 3,
      'Branch Code': 'AD',
      'Branch Name': 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE',
      Cateogry: 1,
    },
    {
      'S NO': 4,
      'Branch Code': 'IM',
      'Branch Name': 'INFORMATION TECHNOLOGY (SS)',
      Cateogry: 1,
    },
    {
      'S NO': 5,
      'Branch Code': 'CM',
      'Branch Name': 'COMPUTER SCIENCE AND ENGINEERING (SS)',
      Cateogry: 1,
    },
    {
      'S NO': 6,
      'Branch Code': 'CB',
      'Branch Name': 'COMPUTER SCIENCE AND BUSSINESS SYSTEM',
      Cateogry: 1,
    },
    {
      'S NO': 7,
      'Branch Code': 'AM',
      'Branch Name': 'COMPUTER SCIENCE AND ENGINEERING (AI AND MACHINE LEARNING)',
      Cateogry: 1,
    },
    {
      'S NO': 8,
      'Branch Code': 'AL',
      'Branch Name': 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING',
      Cateogry: 1,
    },
    {
      'S NO': 9,
      'Branch Code': 'SC',
      'Branch Name': 'COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)',
      Cateogry: 1,
    },
    {
      'S NO': 10,
      'Branch Code': 'CD',
      'Branch Name': 'COMPUTER SCIENCE AND DESIGN',
      Cateogry: 1,
    },
    {
      'S NO': 11,
      'Branch Code': 'AT',
      'Branch Name': 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)',
      Cateogry: 1,
    },
    {
      'S NO': 12,
      'Branch Code': 'CJ',
      'Branch Name': 'M.TECH. COMPUTER SCIENCE AND ENGINEERING (INTEGRATED 5 YEARS)',
      Cateogry: 1,
    },
    {
      'S NO': 13,
      'Branch Code': 'CI',
      'Branch Name': 'COMPUTER SCIENCE & ENGINEERING (INTERENT OF THINGS)',
      Cateogry: 1,
    },
    {
      'S NO': 14,
      'Branch Code': 'CO',
      'Branch Name': 'COMPUTER AND COMMUNICATION ENGINEERING',
      Cateogry: 1,
    },
    {
      'S NO': 15,
      'Branch Code': 'CG',
      'Branch Name':
        'COMPUTER SCIENCE & ENGINEERING (ARTIFICIAL INTELLIGENCE & MACHINE LEARNING (SS))',
      Cateogry: 1,
    },
    {
      'S NO': 16,
      'Branch Code': 'CW',
      'Branch Name': 'COMPUTER SCIENCE AND BUSINESS SYSTEM (SS)',
      Cateogry: 1,
    },
    {
      'S NO': 17,
      'Branch Code': 'CT',
      'Branch Name': 'COMPUTER TECHNOLOGY',
      Cateogry: 1,
    },
    {
      'S NO': 18,
      'Branch Code': 'SE',
      'Branch Name': 'INFORMATION SCIENCE AND ENGINEERING',
      Cateogry: 1,
    },
    {
      'S NO': 19,
      'Branch Code': 'CF',
      'Branch Name': 'COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)',
      Cateogry: 1,
    },
    {
      'S NO': 20,
      'Branch Code': 'CY',
      'Branch Name': 'CYBER SECURITY',
      Cateogry: 1,
    },
    {
      'S NO': 21,
      'Branch Code': 'TS',
      'Branch Name': 'COMPUTER SCIENCE AND TECHNOLOGY',
      Cateogry: 1,
    },
    {
      'S NO': 22,
      'Branch Code': 'SB',
      'Branch Name':
        'COMPUTER SCIENCE AND ENGINEERING (INTERNET OF THINGS AND CYBER SECURITY INCLUDING BLOCK CHAIN TECHNOLOGY)',
      Cateogry: 1,
    },
    {
      'S NO': 23,
      'Branch Code': 'XS',
      'Branch Name': 'COMPUTER SCIENCE AND ENGINEERING (TAMIL)',
      Cateogry: 1,
    },
  ],
  'ELECTRONICS ENGINEERING': [
    {
      'S NO': 1,
      'Branch Code': 'EC',
      'Branch Name': 'ELECTRONICS AND COMMUNICATION ENGINEERING',
      Cateogry: 2,
    },
    {
      'S NO': 2,
      'Branch Code': 'EE',
      'Branch Name': 'ELECTRICAL AND ELECTRONICS ENGINEERING',
      Cateogry: 2,
    },
    {
      'S NO': 3,
      'Branch Code': 'EM',
      'Branch Name': 'ELECTRONICS AND COMMUNICATION ENGINEERING (SS)',
      Cateogry: 2,
    },
    {
      'S NO': 4,
      'Branch Code': 'EI',
      'Branch Name': 'ELECTRONICS AND INSTRUMENTATION ENGINEERING',
      Cateogry: 2,
    },
    {
      'S NO': 5,
      'Branch Code': 'EY',
      'Branch Name': 'ELECTRICAL AND ELECTRONICS ENGINEERING (SS)',
      Cateogry: 2,
    },
    {
      'S NO': 6,
      'Branch Code': 'EV',
      'Branch Name': 'ELECTRONICS & COMMUNICATION ENGINEERING (VLSI DESIGN AND TECHNOLOGY)',
      Cateogry: 2,
    },
    {
      'S NO': 7,
      'Branch Code': 'EA',
      'Branch Name': 'ELECTRONICS & COMMUNICATION ENGINEERING (ADVANCED COMMUNICATION TECHNOLOGY)',
      Cateogry: 2,
    },
    {
      'S NO': 8,
      'Branch Code': 'IY',
      'Branch Name': 'INSTRUMENTATION AND CONTROL ENGINEERING (SS)',
      Cateogry: 2,
    },
    {
      'S NO': 9,
      'Branch Code': 'ES',
      'Branch Name': 'ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)',
      Cateogry: 2,
    },
    {
      'S NO': 10,
      'Branch Code': 'ET',
      'Branch Name': 'ELECTRONICS AND TELECOMMUNICATION ENGINEERING',
      Cateogry: 2,
    },
    {
      'S NO': 11,
      'Branch Code': 'MD',
      'Branch Name': 'MEDICAL ELECTRONICS ENGINEERING',
      Cateogry: 2,
    },
    {
      'S NO': 12,
      'Branch Code': 'IC',
      'Branch Name': 'INSTRUMENTATION AND CONTROL ENGINEERING',
      Cateogry: 2,
    },
  ],
  'MECHANICAL ENGINEERING': [
    {
      'S NO': 1,
      'Branch Code': 'ME',
      'Branch Name': 'MECHANICAL ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 2,
      'Branch Code': 'AE',
      'Branch Name': 'AERONAUTICAL ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 3,
      'Branch Code': 'MZ',
      'Branch Name': 'MECHATRONICS ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 4,
      'Branch Code': 'PR',
      'Branch Name': 'PRODUCTION ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 5,
      'Branch Code': 'MF',
      'Branch Name': 'MECHANICAL ENGINEERING (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 6,
      'Branch Code': 'AU',
      'Branch Name': 'AUTOMOBILE ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 7,
      'Branch Code': 'RA',
      'Branch Name': 'ROBOTICS AND AUTOMATION (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 8,
      'Branch Code': 'MN',
      'Branch Name': 'MANUFACTURING ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 9,
      'Branch Code': 'PT',
      'Branch Name': 'PRINTING TECHNOLOGY',
      Cateogry: 3,
    },
    {
      'S NO': 10,
      'Branch Code': 'IE',
      'Branch Name': 'INDUSTRIAL ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 11,
      'Branch Code': 'RP',
      'Branch Name': 'RUBBER AND PLASTIC TECHNOLOGY',
      Cateogry: 3,
    },
    {
      'S NO': 12,
      'Branch Code': 'MG',
      'Branch Name': 'MECHATRONICS (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 13,
      'Branch Code': 'MS',
      'Branch Name': 'MECHANICAL ENGINEERING (SANDWICH) (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 14,
      'Branch Code': 'RM',
      'Branch Name': 'ROBOTICS AND AUTOMATION',
      Cateogry: 3,
    },
    {
      'S NO': 15,
      'Branch Code': 'AS',
      'Branch Name': 'AUTOMOBILE ENGINEERING (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 16,
      'Branch Code': 'XM',
      'Branch Name': 'MECHANICAL ENGINEERING (TAMIL MEDIUM)',
      Cateogry: 3,
    },
    {
      'S NO': 17,
      'Branch Code': 'MA',
      'Branch Name': 'MATERIAL SCIENCE AND ENGINEERING (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 18,
      'Branch Code': 'MT',
      'Branch Name': 'METALLURGICAL ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 19,
      'Branch Code': 'MI',
      'Branch Name': 'MINING ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 20,
      'Branch Code': 'AO',
      'Branch Name': 'AEROSPACE ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 21,
      'Branch Code': 'PN',
      'Branch Name': 'PRODUCTION ENGINEERING (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 22,
      'Branch Code': 'MY',
      'Branch Name': 'METALLURGICAL ENGINEERING (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 23,
      'Branch Code': 'PA',
      'Branch Name': 'PLASTIC TECHNOLOGY',
      Cateogry: 3,
    },
    {
      'S NO': 24,
      'Branch Code': 'MU',
      'Branch Name': 'MECHANICAL AND AUTOMATION ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 25,
      'Branch Code': 'CR',
      'Branch Name': 'CERAMIC TECHNOLOGY (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 26,
      'Branch Code': 'PS',
      'Branch Name': 'PRODUCTION ENGINEERING (SANDWICH) (SS)',
      Cateogry: 3,
    },
    {
      'S NO': 27,
      'Branch Code': 'IN',
      'Branch Name': 'INDUSTRIAL ENGINEERING AND MANAGEMENT',
      Cateogry: 3,
    },
    {
      'S NO': 28,
      'Branch Code': 'MM',
      'Branch Name': 'MECHANICAL ENGINEERING (MANUFACTURING)',
      Cateogry: 3,
    },
    {
      'S NO': 29,
      'Branch Code': 'SF',
      'Branch Name': 'SAFETY AND FIRE ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 30,
      'Branch Code': 'MC',
      'Branch Name': 'MECHATRONICS',
      Cateogry: 3,
    },
    {
      'S NO': 31,
      'Branch Code': 'MO',
      'Branch Name': 'MECHANICAL AND MECHATRONICS ENGINEERING (ADDITIVE MANUFACTURING)',
      Cateogry: 3,
    },
    {
      'S NO': 33,
      'Branch Code': 'MR',
      'Branch Name': 'MARINE ENGINEERING',
      Cateogry: 3,
    },
    {
      'S NO': 34,
      'Branch Code': 'AG',
      'Branch Name': 'AGRICULTURE ENGINEERING',
      Cateogry: 3,
    },
  ],
  'CIVIL ENGINEERING': [
    {
      'S NO': 1,
      'Branch Code': 'CE',
      'Branch Name': 'CIVIL  ENGINEERING',
      Cateogry: 4,
    },
    {
      'S NO': 2,
      'Branch Code': 'CN',
      'Branch Name': 'CIVIL  ENGINEERING (SS)',
      Cateogry: 4,
    },
    {
      'S NO': 3,
      'Branch Code': 'XC',
      'Branch Name': 'CIVIL ENGINEERING (TAMIL MEDIUM)',
      Cateogry: 4,
    },
    {
      'S NO': 4,
      'Branch Code': 'CZ',
      'Branch Name': 'CIVIL AND STRUCTUTURAL ENGINEERING',
      Cateogry: 4,
    },
  ],

  'BIO MEDICAL ENGINEERING': [
    {
      'S NO': 1,
      'Branch Code': 'BM',
      'Branch Name': 'BIO MEDICAL ENGINEERING',
      Cateogry: 5,
    },
    {
      'S NO': 2,
      'Branch Code': 'CH',
      'Branch Name': 'CHEMICAL  ENGINEERING',
      Cateogry: 5,
    },
    {
      'S NO': 3,
      'Branch Code': 'BT',
      'Branch Name': 'BIO TECHNOLOGY',
      Cateogry: 5,
    },
    {
      'S NO': 4,
      'Branch Code': 'IB',
      'Branch Name': 'INDUSTRIAL BIO TECHNOLOGY',
      Cateogry: 5,
    },
    {
      'S NO': 5,
      'Branch Code': 'BY',
      'Branch Name': 'BIO MEDICAL ENGINEERING (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 6,
      'Branch Code': 'CL',
      'Branch Name': 'CHEMICAL  ENGINEERING (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 7,
      'Branch Code': 'BS',
      'Branch Name': 'BIO TECHNOLOGY (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 8,
      'Branch Code': 'FS',
      'Branch Name': 'FOOD TECHNOLOGY (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 9,
      'Branch Code': 'PP',
      'Branch Name': 'PETROLEUM ENGINEERING AND TECHNOLOGY (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 10,
      'Branch Code': 'PE',
      'Branch Name': 'PETROLEUM ENGINEERING',
      Cateogry: 5,
    },
    {
      'S NO': 11,
      'Branch Code': 'CC',
      'Branch Name': 'CHEMICAL AND ELECTRO CHEMICAL ENGINEERING (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 12,
      'Branch Code': 'FD',
      'Branch Name': 'FOOD TECHNOLOGY',
      Cateogry: 5,
    },
    {
      'S NO': 13,
      'Branch Code': 'IS',
      'Branch Name': 'INDUSTRIAL BIO TECHNOLOGY (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 14,
      'Branch Code': 'PC',
      'Branch Name': 'PETRO CHEMICAL TECHNOLOGY',
      Cateogry: 5,
    },
    {
      'S NO': 15,
      'Branch Code': 'BC',
      'Branch Name': 'BIO TECHNOLOGY AND BIO CHEMICAL ENGINEERING',
      Cateogry: 5,
    },
    {
      'S NO': 16,
      'Branch Code': 'PM',
      'Branch Name': 'PHARMACEUTICAL TECHNOLOGY (SS)',
      Cateogry: 5,
    },
    {
      'S NO': 17,
      'Branch Code': 'PH',
      'Branch Name': 'PHARMACEUTICAL TECHNOLOGY',
      Cateogry: 5,
    },
  ],
  'TEXTILE TECHNOLOGY': [
    {
      'S NO': 1,
      'Branch Code': 'TX',
      'Branch Name': 'TEXTILE TECHNOLOGY',
      Cateogry: 6,
    },
    {
      'S NO': 2,
      'Branch Code': 'FY',
      'Branch Name': 'FASHION TECHNOLOGY (SS)',
      Cateogry: 6,
    },
    {
      'S NO': 3,
      'Branch Code': 'FT',
      'Branch Name': 'FASHION TECHNOLOGY',
      Cateogry: 6,
    },
    {
      'S NO': 4,
      'Branch Code': 'TT',
      'Branch Name': 'TEXTILE TECHNOLOGY (SS)',
      Cateogry: 6,
    },
    {
      'S NO': 5,
      'Branch Code': 'TC',
      'Branch Name': 'TEXTILE CHEMISTRY',
      Cateogry: 6,
    },
    {
      'S NO': 6,
      'Branch Code': 'HT',
      'Branch Name': 'HANDLOOM AND TEXTILE TECHNOLOGY',
      Cateogry: 6,
    },
  ],
  OTHERS: [
    {
      'S NO': 1,
      'Branch Code': 'GI',
      'Branch Name': 'GEO INFORMATICS',
      Cateogry: 7,
    },
    {
      'S NO': 2,
      'Branch Code': 'LE',
      'Branch Name': 'LEATHER TECHNOLOGY',
      Cateogry: 7,
    },
    {
      'S NO': 3,
      'Branch Code': 'AP',
      'Branch Name': 'APPAREL TECHNOLOGY (SS)',
      Cateogry: 7,
    },
    {
      'S NO': 4,
      'Branch Code': 'EN',
      'Branch Name': 'ENVIRONMENTAL ENGINEERING',
      Cateogry: 7,
    },
  ],
};
